spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/do-an-lang-thang
    username: root
    password: illusion
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  #        generate_statistics: true
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

cloud:
  aws:
    bucket:
      name: langthang-user-photos
    credentials:
      access-key:
      secret-key:
    region:
      static: ap-southeast-1
    stack:
      auto: false
    public:
      base-url: https://${cloud.aws.bucket.name}.s3-${cloud.aws.region.static}.amazonaws.com

application:
  image:
    support-type: image/png,image/jpg,image/jpeg

security:
  jwt:
    token:
      prefix: Bearer
      secret-key: WeAreBrother
      expire-length: 100000
  oauth2:
    google:
      client-id: 545452035521-c4eljpuu1281eml2ci6kaud39s5kc9ct.apps.googleusercontent.com
